DROP TABLE Enrollment CASCADE CONSTRAINTS;
DROP TABLE Lessons CASCADE CONSTRAINTS;
DROP TABLE Equipment CASCADE CONSTRAINTS;
DROP TABLE Courses CASCADE CONSTRAINTS;
DROP TABLE Students CASCADE CONSTRAINTS;
DROP TABLE Teachers CASCADE CONSTRAINTS;
