DROP SCHEMA IF EXISTS MusicLesson CASCADE;
CREATE SCHEMA MusicLesson;
SET search_path TO MusicLesson;


DROP TABLE IF EXISTS Teacher CASCADE;
CREATE TABLE Teacher (
    TId SERIAL PRIMARY KEY,
    TName VARCHAR(100) NOT NULL,
    Salary NUMERIC(10,2),
    Email VARCHAR(150)
);


DROP TABLE IF EXISTS Student CASCADE;
CREATE TABLE Student (
    SId SERIAL PRIMARY KEY,
    SName VARCHAR(100) NOT NULL,
    Address VARCHAR(200)
);


DROP TABLE IF EXISTS Class CASCADE;
CREATE TABLE Class (
    CId SERIAL PRIMARY KEY,
    CName VARCHAR(100) NOT NULL,
    MaxStudents INT
);


DROP TABLE IF EXISTS Equipment CASCADE;
CREATE TABLE Equipment (
    EId SERIAL PRIMARY KEY,
    Type VARCHAR(50),
    Color VARCHAR(50)
);


DROP TABLE IF EXISTS Activity CASCADE;
CREATE TABLE Activity (
    AId SERIAL PRIMARY KEY,
    Place VARCHAR(100),
    ActivityDate DATE,
    Description VARCHAR(255)
);


DROP TABLE IF EXISTS Lesson CASCADE;
CREATE TABLE Lesson (
    LId SERIAL PRIMARY KEY,
    LName VARCHAR(100) NOT NULL,
    Duration INT,
    LessonType VARCHAR(50),
    openDate DATE,
    CId INT REFERENCES Class(CId) ON DELETE SET NULL,
    TId INT REFERENCES Teacher(TId) ON DELETE SET NULL
);



DROP TABLE IF EXISTS isLearning CASCADE;
CREATE TABLE isLearning (
    SId INT REFERENCES Student(SId) ON DELETE CASCADE,
    LId INT REFERENCES Lesson(LId) ON DELETE CASCADE,
    PRIMARY KEY (SId, LId)
);

DROP TABLE IF EXISTS ParticipatesIn CASCADE;
CREATE TABLE ParticipatesIn (
    SId INT REFERENCES Student(SId) ON DELETE CASCADE,
    AId INT REFERENCES Activity(AId) ON DELETE CASCADE,
    PRIMARY KEY (SId, AId)
);

DROP TABLE IF EXISTS IsHaving CASCADE;
CREATE TABLE IsHaving (
    CId INT REFERENCES Class(CId) ON DELETE CASCADE,
    EId INT REFERENCES Equipment(EId) ON DELETE CASCADE,
    PRIMARY KEY (CId, EId)
);


