insert into student (sname, address) values ('Barri Raycroft', '8 Sutteridge Court');
insert into student (sname, address) values ('Cooper Videler', '2 Lakewood Gardens Court');
insert into student (sname, address) values ('Aeriela Aronovich', '1 Ilene Point');
insert into student (sname, address) values ('Julianne Gartell', '53457 Esker Road');
insert into student (sname, address) values ('Clemens Tondeur', '313 Kropf Crossing');
insert into student (sname, address) values ('Isahella O''Dogherty', '71491 Northwestern Lane');
insert into student (sname, address) values ('Jamill Currm', '773 Village Circle');
insert into student (sname, address) values ('Wittie Ham', '076 Loomis Road');
insert into student (sname, address) values ('Rog Allans', '80 Shoshone Parkway');
insert into student (sname, address) values ('Kirbee Wills', '91704 Forest Junction');
insert into student (sname, address) values ('Filberto Mylechreest', '39 Golden Leaf Pass');
insert into student (sname, address) values ('Ludwig Stathers', '6913 Dapin Lane');
insert into student (sname, address) values ('Kristofer Wallicker', '5 Duke Place');
insert into student (sname, address) values ('Drucie Ruberry', '5 Marquette Court');
insert into student (sname, address) values ('Ferd Kynaston', '6 Surrey Court');
insert into student (sname, address) values ('Maritsa Yedy', '45316 Fairfield Trail');
insert into student (sname, address) values ('Ailey Najara', '025 Algoma Road');
insert into student (sname, address) values ('Ephrayim Shortin', '7173 Florence Parkway');
insert into student (sname, address) values ('Arturo Lage', '5353 Debra Avenue');
insert into student (sname, address) values ('Knox Guittet', '15352 Charing Cross Junction');
insert into student (sname, address) values ('Dionysus Corran', '84 Straubel Drive');
insert into student (sname, address) values ('Philomena Seamark', '66995 Fulton Court');
insert into student (sname, address) values ('Bev Morrowe', '27418 Blaine Drive');
insert into student (sname, address) values ('Leesa Peartree', '18 Main Park');
insert into student (sname, address) values ('Berry Pogosian', '65 Scott Point');
insert into student (sname, address) values ('Erda Kendal', '9 Badeau Place');
insert into student (sname, address) values ('Sherri Libero', '3958 Lotheville Drive');
insert into student (sname, address) values ('Brynne Westhoff', '4 Ruskin Hill');
insert into student (sname, address) values ('Carver Liffe', '5031 Calypso Place');
insert into student (sname, address) values ('Lucky Fallowfield', '58 Hayes Way');
insert into student (sname, address) values ('Angelico Farrance', '09375 Eliot Street');
insert into student (sname, address) values ('Arlene Marrison', '146 Green Parkway');
insert into student (sname, address) values ('Rouvin Biagioni', '295 Hoard Road');
insert into student (sname, address) values ('Emmie Denial', '02 Logan Avenue');
insert into student (sname, address) values ('Felic Witham', '19 Hollow Ridge Parkway');
insert into student (sname, address) values ('Bernette Gerasch', '14 Cordelia Place');
insert into student (sname, address) values ('Shay Zannutti', '796 Bunting Junction');
insert into student (sname, address) values ('Gothart Knevit', '76 Cordelia Terrace');
insert into student (sname, address) values ('Kimberlee Gibbings', '2 Sherman Plaza');
insert into student (sname, address) values ('Debbie Reichhardt', '182 5th Lane');
insert into student (sname, address) values ('Wes Eleshenar', '82 Sauthoff Hill');
insert into student (sname, address) values ('Lane Petters', '9 Carpenter Hill');
insert into student (sname, address) values ('Cammy Entwhistle', '847 Eastwood Park');
insert into student (sname, address) values ('Skip Dorking', '1 Kropf Center');
insert into student (sname, address) values ('Rakel Lincke', '99174 Twin Pines Center');
insert into student (sname, address) values ('Kara Curee', '803 Butternut Street');
insert into student (sname, address) values ('Oberon Court', '92179 Burning Wood Drive');
insert into student (sname, address) values ('Batholomew Sybry', '3264 Mitchell Parkway');
insert into student (sname, address) values ('Mildred Couve', '8036 Ridge Oak Alley');
insert into student (sname, address) values ('Carlos Dibson', '1 Dawn Terrace');
insert into student (sname, address) values ('Corella Le Friec', '08003 Briar Crest Point');
insert into student (sname, address) values ('Reeba Bordis', '06773 Magdeline Road');
insert into student (sname, address) values ('Karine Cape', '82194 Pond Center');
insert into student (sname, address) values ('Beilul Statton', '166 Lyons Junction');
insert into student (sname, address) values ('Mortie Dollar', '48 Hanson Court');
insert into student (sname, address) values ('Joice Crossan', '59225 Merrick Street');
insert into student (sname, address) values ('Clem Joubert', '06672 Harper Point');
insert into student (sname, address) values ('Renate Bentham3', '2 Hauk Street');
insert into student (sname, address) values ('Maxy Janeway', '0119 Merrick Alley');
insert into student (sname, address) values ('Ettore Ocklin', '7853 Nelson Parkway');
insert into student (sname, address) values ('Perle Lattimer', '085 Huxley Court');
insert into student (sname, address) values ('Kassandra Heisman', '18880 Roth Point');
insert into student (sname, address) values ('Dill Gooden', '26 Mitchell Road');
insert into student (sname, address) values ('Isidore Hansell', '95192 Jana Junction');
insert into student (sname, address) values ('Dewey Crighton', '2 Dayton Avenue');
insert into student (sname, address) values ('Odella Spelman', '7313 Bultman Parkway');
insert into student (sname, address) values ('Thorny Bowering', '92587 Comanche Terrace');
insert into student (sname, address) values ('Viva Meneyer', '42 Texas Park');
insert into student (sname, address) values ('Bryana Martini', '915 Scott Trail');
insert into student (sname, address) values ('Rosita Dickings', '474 Gina Way');
insert into student (sname, address) values ('Niki McCarlich', '6 Lotheville Street');
insert into student (sname, address) values ('Harv Lamp', '07 Elmside Road');
insert into student (sname, address) values ('Robby Malthouse', '7931 Oak Circle');
insert into student (sname, address) values ('Marleah Scoyne', '6066 Saint Paul Pass');
insert into student (sname, address) values ('Wyndham Tremouille', '30466 Grayhawk Junction');
insert into student (sname, address) values ('Gerri Brummell', '17 Transport Pass');
insert into student (sname, address) values ('Layney Holley', '6235 Commercial Drive');
insert into student (sname, address) values ('Darryl O''Mahoney', '41 Bluejay Court');
insert into student (sname, address) values ('York Chiplin', '50 Buhler Way');
insert into student (sname, address) values ('Harcourt Hamber', '78 Summer Ridge Parkway');
insert into student (sname, address) values ('Wade Arnot', '422 Mcbride Pass');
insert into student (sname, address) values ('Westley Meharry', '98 Bobwhite Terrace');
insert into student (sname, address) values ('Kristal Orange', '7 Kropf Alley');
insert into student (sname, address) values ('Tabitha Penvarden', '90 Sommers Alley');
insert into student (sname, address) values ('Pierre Hayller', '96 Coolidge Crossing');
insert into student (sname, address) values ('Lissie Davidge', '6935 Troy Plaza');
insert into student (sname, address) values ('Karlie Vickery', '98 Rowland Trail');
insert into student (sname, address) values ('Nikaniki Kinforth', '1519 Ruskin Alley');
insert into student (sname, address) values ('Averyl Espy', '4 Banding Center');
insert into student (sname, address) values ('Etienne Spaice', '31 Tomscot Plaza');
insert into student (sname, address) values ('Molli Elcombe', '7714 Arrowood Street');
insert into student (sname, address) values ('Wilmar Franceschelli', '6 Farmco Street');
insert into student (sname, address) values ('Vinnie Masic', '5 Welch Circle');
insert into student (sname, address) values ('Ciro Florence', '3 Chinook Way');
insert into student (sname, address) values ('Car Illing', '3796 Basil Hill');
insert into student (sname, address) values ('Dore Mileham', '378 Russell Court');
insert into student (sname, address) values ('Giulietta Simpkin', '20 Eagle Crest Drive');
insert into student (sname, address) values ('Dugald Vedstra', '0408 Alpine Hill');
insert into student (sname, address) values ('Torin Birwhistle', '3022 Meadow Ridge Park');
insert into student (sname, address) values ('Berri Mattke', '52930 Vahlen Way');
insert into student (sname, address) values ('Brittaney Zupo', '25 Lakewood Gardens Drive');
insert into student (sname, address) values ('Lionel Guilbert', '8690 Grasskamp Park');
insert into student (sname, address) values ('Marnia Sheron', '4 Mendota Court');
insert into student (sname, address) values ('Kristoffer Kefford', '7050 Cody Court');
insert into student (sname, address) values ('Lorrayne Deaconson', '06 Maywood Terrace');
insert into student (sname, address) values ('Allx Costanza', '525 Anderson Street');
insert into student (sname, address) values ('Rad Paddefield', '6 Independence Drive');
insert into student (sname, address) values ('Trumann Pocke', '76441 Maple Hill');
insert into student (sname, address) values ('Warden Jeaffreson', '80382 Westport Center');
insert into student (sname, address) values ('Dun Armitage', '0 Moose Circle');
insert into student (sname, address) values ('Halsey Noriega', '05992 Arapahoe Plaza');
insert into student (sname, address) values ('Bartlett Gonthard', '548 American Plaza');
insert into student (sname, address) values ('Teresa Loveredge', '999 Tomscot Drive');
insert into student (sname, address) values ('Genny Audibert', '0 Onsgard Way');
insert into student (sname, address) values ('Tirrell Gerhartz', '16 Waubesa Terrace');
insert into student (sname, address) values ('Mervin Milesap', '37 Mitchell Parkway');
insert into student (sname, address) values ('Nancy Blades', '242 Glacier Hill Court');
insert into student (sname, address) values ('Hamish Golds', '8532 Victoria Road');
insert into student (sname, address) values ('Costanza Brunt', '13 Milwaukee Plaza');
insert into student (sname, address) values ('Heywood Ragsdall', '07103 Alpine Point');
insert into student (sname, address) values ('Romain Dovydenas', '47316 Grayhawk Drive');
insert into student (sname, address) values ('Rubina Cordes', '8 Birchwood Court');
insert into student (sname, address) values ('Shoshana McCrow', '7783 Comanche Parkway');
insert into student (sname, address) values ('Winnifred Vatcher', '0 Homewood Plaza');
insert into student (sname, address) values ('Charin Swayne', '78672 Myrtle Point');
insert into student (sname, address) values ('Rutter Wealleans', '420 Clarendon Point');
insert into student (sname, address) values ('Carmelia Husbands', '4 Ridge Oak Place');
insert into student (sname, address) values ('Breanne Calladine', '5665 6th Alley');
insert into student (sname, address) values ('Gun Stookes', '3 Morning Road');
insert into student (sname, address) values ('Lowrance Lutsch', '933 Bayside Way');
insert into student (sname, address) values ('Lolly Huckleby', '47 Iowa Pass');
insert into student (sname, address) values ('Tobiah Winkworth', '1502 Park Meadow Way');
insert into student (sname, address) values ('Thadeus Inde', '692 Warner Plaza');
insert into student (sname, address) values ('Ashia Inchboard', '53 Arapahoe Trail');
insert into student (sname, address) values ('Josepha Fauning', '0 Kropf Lane');
insert into student (sname, address) values ('Reuven Le Grys', '8 Forest Road');
insert into student (sname, address) values ('Hanan Negro', '8719 Esch Crossing');
insert into student (sname, address) values ('Sampson Sherbrook', '9 Oriole Park');
insert into student (sname, address) values ('Jaime Barbary', '9220 Lotheville Road');
insert into student (sname, address) values ('Killy Huggon', '2825 Maryland Drive');
insert into student (sname, address) values ('Darrick Clarridge', '726 Valley Edge Avenue');
insert into student (sname, address) values ('Rockie Muir', '9850 New Castle Junction');
insert into student (sname, address) values ('Mickie Anthon', '7 Knutson Junction');
insert into student (sname, address) values ('Kerwinn Don', '340 Transport Street');
insert into student (sname, address) values ('Jeremie Olivari', '9 Esch Place');
insert into student (sname, address) values ('Modesty Denson', '9 Mcbride Point');
insert into student (sname, address) values ('Mandy Toopin', '5 Badeau Parkway');
insert into student (sname, address) values ('Judas Glamart', '4487 Clarendon Street');
insert into student (sname, address) values ('Julius Benard', '9 Maryland Way');
insert into student (sname, address) values ('Eberhard Pyer', '20 7th Trail');
insert into student (sname, address) values ('Iolanthe Cashmore', '15 Helena Parkway');
insert into student (sname, address) values ('Jedd O''Henecan', '3784 Glacier Hill Trail');
insert into student (sname, address) values ('Cassaundra Langabeer', '1398 Gina Way');
insert into student (sname, address) values ('Prisca Geerdts', '247 Sheridan Alley');
insert into student (sname, address) values ('Colly Kellock', '90 Mockingbird Pass');
insert into student (sname, address) values ('Bernie Reggler', '5610 Waxwing Road');
insert into student (sname, address) values ('Alison Winwood', '433 Clyde Gallagher Street');
insert into student (sname, address) values ('August Bricket', '072 Sunnyside Parkway');
insert into student (sname, address) values ('Cordey Shrimplin', '8 Sutherland Pass');
insert into student (sname, address) values ('Florenza Ardron', '6 Jenna Hill');
insert into student (sname, address) values ('Stepha Arlt', '94948 Waywood Drive');
insert into student (sname, address) values ('Becca Round', '9370 Texas Avenue');
insert into student (sname, address) values ('Amalita Sellman', '9490 Hansons Way');
insert into student (sname, address) values ('Kim Yesichev', '30 Derek Junction');
insert into student (sname, address) values ('Frannie Doveston', '3 Pond Pass');
insert into student (sname, address) values ('Laurent Van Brug', '574 Warner Trail');
insert into student (sname, address) values ('Tab Backhurst', '707 Iowa Drive');
insert into student (sname, address) values ('Adriane Palethorpe', '452 Melby Crossing');
insert into student (sname, address) values ('Humfrey Maddin', '18 6th Circle');
insert into student (sname, address) values ('Anya Abbay', '4656 Forest Dale Pass');
insert into student (sname, address) values ('Dolph Kunc', '47 Dawn Crossing');
insert into student (sname, address) values ('Tirrell Hove', '73 Scofield Circle');
insert into student (sname, address) values ('Moina Flewitt', '581 Waxwing Terrace');
insert into student (sname, address) values ('Calhoun Fantonetti', '77295 Boyd Court');
insert into student (sname, address) values ('Decca Popping', '38 Hovde Center');
insert into student (sname, address) values ('Andrea Nuemann', '2593 Aberg Parkway');
insert into student (sname, address) values ('Clark Balwin', '3 Mitchell Junction');
insert into student (sname, address) values ('Heall Feige', '55 Acker Road');
insert into student (sname, address) values ('Marsha Gethin', '9793 Sycamore Lane');
insert into student (sname, address) values ('Falito Kemm', '9 Elka Parkway');
insert into student (sname, address) values ('Mariana Povele', '82 John Wall Way');
insert into student (sname, address) values ('Ab Scyner', '5 Talmadge Point');
insert into student (sname, address) values ('Rea Ibbitson', '77580 Esker Drive');
insert into student (sname, address) values ('Shelly Dufour', '718 Ronald Regan Court');
insert into student (sname, address) values ('Raffarty Stuckford', '186 Graceland Crossing');
insert into student (sname, address) values ('Karlene Winterflood', '2765 1st Trail');
insert into student (sname, address) values ('Roi Kerss', '5673 Glendale Terrace');
insert into student (sname, address) values ('Ashlee Costerd', '13 Karstens Avenue');
insert into student (sname, address) values ('Simone Roscher', '9 Cody Avenue');
insert into student (sname, address) values ('Stanfield Prestie', '83 Delaware Parkway');
insert into student (sname, address) values ('Merle Felgat', '260 Havey Center');
insert into student (sname, address) values ('Jeremie Rainy', '750 Kropf Point');
insert into student (sname, address) values ('Lettie Knyvett', '6 Bluejay Junction');
insert into student (sname, address) values ('Laurette Phillpotts', '39781 Lawn Court');
insert into student (sname, address) values ('Aguistin Degoy', '69848 Calypso Center');
insert into student (sname, address) values ('Hanson Gecks', '67 Meadow Valley Lane');
insert into student (sname, address) values ('Maxie Spoerl', '0164 Armistice Terrace');
insert into student (sname, address) values ('Fulvia Pothecary', '84 Harper Hill');
insert into student (sname, address) values ('Olenolin Coch', '31785 Arizona Avenue');
insert into student (sname, address) values ('Carlotta Camm', '44535 Victoria Park');
insert into student (sname, address) values ('Gussi Lethby', '885 Dawn Place');
insert into student (sname, address) values ('Anders Gumery', '25214 Carberry Drive');
insert into student (sname, address) values ('Lauritz MacAllen', '667 Leroy Lane');
insert into student (sname, address) values ('Felice MacCaffrey', '1188 Barnett Circle');
insert into student (sname, address) values ('Phil Tattersall', '1 Becker Court');
insert into student (sname, address) values ('Garnet Meffin', '55 Brown Crossing');
insert into student (sname, address) values ('Karney Murdoch', '41 Buena Vista Court');
insert into student (sname, address) values ('Rose Nowill', '9046 Golf Circle');
insert into student (sname, address) values ('Jsandye Da Costa', '6551 Harbort Street');
insert into student (sname, address) values ('Benoite Stroulger', '1760 Crownhardt Parkway');
insert into student (sname, address) values ('Ilsa Ardley', '9 Iowa Crossing');
insert into student (sname, address) values ('Willi Muccino', '18552 Barby Point');
insert into student (sname, address) values ('Shanan Sneaker', '7697 Harbort Street');
insert into student (sname, address) values ('Auguste Kleinzweig', '67254 Stoughton Crossing');
insert into student (sname, address) values ('Tann Cleatherow', '1 Holy Cross Terrace');
insert into student (sname, address) values ('Tab Connow', '95 Goodland Drive');
insert into student (sname, address) values ('Cullan Chifney', '50422 Artisan Alley');
insert into student (sname, address) values ('Lesley Gusney', '59257 Kings Trail');
insert into student (sname, address) values ('Udall Overstreet', '2 Fremont Terrace');
insert into student (sname, address) values ('Anthe Chestney', '2 Basil Terrace');
insert into student (sname, address) values ('Eugenius Lecount', '49650 Utah Terrace');
insert into student (sname, address) values ('Gwynne Arthy', '7404 Mitchell Way');
insert into student (sname, address) values ('Forester Schermick', '06 Green Ridge Lane');
insert into student (sname, address) values ('Penelope Routham', '7759 Bashford Way');
insert into student (sname, address) values ('Jean Rosenstengel', '63217 Anhalt Way');
insert into student (sname, address) values ('Josee Filippov', '02 Eliot Terrace');
insert into student (sname, address) values ('Parrnell Castagne', '4 Doe Crossing Center');
insert into student (sname, address) values ('Artus Curnnok', '0310 Fordem Alley');
insert into student (sname, address) values ('Saunder Vahl', '04 Elka Drive');
insert into student (sname, address) values ('Germana Licciardo', '8 Straubel Drive');
insert into student (sname, address) values ('Meredith Youle', '161 Old Gate Crossing');
insert into student (sname, address) values ('Rustin McKeand', '8 Forest Run Pass');
insert into student (sname, address) values ('Jonathon Ickov', '69 Wayridge Way');
insert into student (sname, address) values ('Bliss Oxley', '61744 Bashford Circle');
insert into student (sname, address) values ('Jere Glancy', '3 Vidon Center');
insert into student (sname, address) values ('Louisa Gillies', '416 Jana Point');
insert into student (sname, address) values ('Adolpho Harniman', '584 Sullivan Plaza');
insert into student (sname, address) values ('Emera Bearcroft', '34443 Westridge Place');
insert into student (sname, address) values ('Gunilla Classen', '4465 Redwing Parkway');
insert into student (sname, address) values ('Maddi Fazakerley', '01668 Merry Circle');
insert into student (sname, address) values ('Arlinda Leaver', '294 Westend Street');
insert into student (sname, address) values ('Denyse Nellen', '09 Fair Oaks Parkway');
insert into student (sname, address) values ('Jennee Veldens', '8559 Charing Cross Center');
insert into student (sname, address) values ('Izzy Robic', '00768 Shasta Terrace');
insert into student (sname, address) values ('Griffie Weller', '2770 Milwaukee Place');
insert into student (sname, address) values ('Tad Crinson', '601 Vidon Plaza');
insert into student (sname, address) values ('Octavia Moughtin', '2 Debra Hill');
insert into student (sname, address) values ('Oralle Dowda', '19616 Northridge Road');
insert into student (sname, address) values ('Filippa Silverstone', '83338 Carberry Plaza');
insert into student (sname, address) values ('Darell Rewcastle', '44 Mesta Crossing');
insert into student (sname, address) values ('Lukas McInally', '5 Mallory Avenue');
insert into student (sname, address) values ('Cleo Bordone', '47358 Ludington Way');
insert into student (sname, address) values ('Blinni Kubala', '5434 Luster Plaza');
insert into student (sname, address) values ('Moselle Vasse', '46807 Daystar Avenue');
insert into student (sname, address) values ('Melly Andriulis', '029 Evergreen Court');
insert into student (sname, address) values ('Roberta Sweetman', '8 Spenser Terrace');
insert into student (sname, address) values ('Mitchell Busen', '8115 Brown Road');
insert into student (sname, address) values ('Tracee Antonov', '761 Mendota Terrace');
insert into student (sname, address) values ('Amalee Westby', '5 Truax Road');
insert into student (sname, address) values ('Ephraim Kohrt', '613 Hagan Trail');
insert into student (sname, address) values ('Benedicta Fenna', '2578 Oriole Plaza');
insert into student (sname, address) values ('Garland Antrag', '6 Scoville Pass');
insert into student (sname, address) values ('Rina Deacock', '892 Hollow Ridge Road');
insert into student (sname, address) values ('Chastity Milliken', '61367 Fulton Place');
insert into student (sname, address) values ('Siward Hurrell', '2 Carpenter Trail');
insert into student (sname, address) values ('Horace Banasevich', '52003 Sherman Place');
insert into student (sname, address) values ('Murray Shorto', '636 Bartillon Drive');
insert into student (sname, address) values ('Carey Minget', '45 Crescent Oaks Street');
insert into student (sname, address) values ('Ketty Abrashkin', '990 Ridgeway Circle');
insert into student (sname, address) values ('Ethelin Amyes', '68564 Gateway Junction');
insert into student (sname, address) values ('Tamera Jiles', '865 Eastwood Drive');
insert into student (sname, address) values ('Lancelot Hullin', '649 Bellgrove Alley');
insert into student (sname, address) values ('Elvina Cowell', '434 New Castle Trail');
insert into student (sname, address) values ('Koenraad Newe', '2968 Garrison Avenue');
insert into student (sname, address) values ('Vonni Crowdson', '77 Forster Junction');
insert into student (sname, address) values ('Silvain Farrant', '40 Rusk Drive');
insert into student (sname, address) values ('Darbie Gwillyam', '5 Mcbride Parkway');
insert into student (sname, address) values ('Horace Selcraig', '27 Hazelcrest Center');
insert into student (sname, address) values ('Arline Ommanney', '0954 Summer Ridge Trail');
insert into student (sname, address) values ('Garner Hunnable', '1437 Fordem Road');
insert into student (sname, address) values ('Robbin Wingate', '76 Green Trail');
insert into student (sname, address) values ('Norah Lainton', '61312 Miller Drive');
insert into student (sname, address) values ('Patrizius Vogeler', '0 Hoard Pass');
insert into student (sname, address) values ('Gaynor Aleksankov', '1007 Russell Alley');
insert into student (sname, address) values ('Jeanelle Gott', '73298 Parkside Avenue');
insert into student (sname, address) values ('Nehemiah Killich', '8 Glendale Court');
insert into student (sname, address) values ('Zedekiah Batie', '067 Ryan Road');
insert into student (sname, address) values ('Abey Gumn', '605 Roth Lane');
insert into student (sname, address) values ('Fraze Danet', '3 Ilene Avenue');
insert into student (sname, address) values ('Cecilius Dackombe', '917 Utah Terrace');
insert into student (sname, address) values ('Lilyan Worcs', '04209 Morrow Place');
insert into student (sname, address) values ('Iggy Inskipp', '9 Marquette Crossing');
insert into student (sname, address) values ('Abigale Strowther', '48101 Stuart Road');
insert into student (sname, address) values ('Zena Workman', '48707 Hollow Ridge Parkway');
insert into student (sname, address) values ('Ferguson Klewi', '2 Twin Pines Court');
insert into student (sname, address) values ('Brody Ferrillo', '95447 Dunning Terrace');
insert into student (sname, address) values ('Pepita Zecchinelli', '64 Loeprich Crossing');
insert into student (sname, address) values ('Fredrika Worcs', '4 Spenser Place');
insert into student (sname, address) values ('Cheri Woodrooffe', '68897 Elmside Way');
insert into student (sname, address) values ('Bengt Tolson', '63542 Sommers Park');
insert into student (sname, address) values ('Warner Bramhill', '66541 Ruskin Place');
insert into student (sname, address) values ('Hermy Headington', '97 Independence Crossing');
insert into student (sname, address) values ('Algernon Champley', '3530 Bay Lane');
insert into student (sname, address) values ('Georgianna Gianetti', '147 Ruskin Terrace');
insert into student (sname, address) values ('Maurise Castillon', '76214 Goodland Alley');
insert into student (sname, address) values ('Nelia Casham', '05908 Hoepker Parkway');
insert into student (sname, address) values ('Say Borrow', '4 Veith Way');
insert into student (sname, address) values ('Abra Giorgietto', '063 Karstens Plaza');
insert into student (sname, address) values ('Bethanne Boothroyd', '2 Pearson Avenue');
insert into student (sname, address) values ('Tull Gissing', '731 Dennis Court');
insert into student (sname, address) values ('Irena Gostage', '56233 Farmco Way');
insert into student (sname, address) values ('Madalyn Vedyashkin', '47758 Orin Center');
insert into student (sname, address) values ('Lisabeth Callaghan', '8090 Saint Paul Park');
insert into student (sname, address) values ('Alexina Durnall', '93 Springs Plaza');
insert into student (sname, address) values ('Adams Tethcote', '45485 Derek Drive');
insert into student (sname, address) values ('Katheryn Pawelski', '02 Independence Hill');
insert into student (sname, address) values ('Pegeen Gianni', '41 Monument Avenue');
insert into student (sname, address) values ('Jsandye Simmens', '71 Graedel Avenue');
insert into student (sname, address) values ('Hamish Fenner', '9 Steensland Point');
insert into student (sname, address) values ('Claiborn Conigsby', '09120 Portage Circle');
insert into student (sname, address) values ('Adriano Gabbitus', '502 Tennyson Way');
insert into student (sname, address) values ('Annalise Buckthorp', '88382 Ramsey Court');
insert into student (sname, address) values ('Spike Simeonov', '76 Anhalt Lane');
insert into student (sname, address) values ('Colman Figures', '552 Arapahoe Crossing');
insert into student (sname, address) values ('Torr Marton', '63 Columbus Alley');
insert into student (sname, address) values ('Cleopatra Treanor', '8999 Cardinal Circle');
insert into student (sname, address) values ('Gerianna Winson', '8120 Briar Crest Way');
insert into student (sname, address) values ('Harriot Haugen', '6200 Moulton Drive');
insert into student (sname, address) values ('Sheena Jolliman', '22 Monument Center');
insert into student (sname, address) values ('Liza Branchett', '3486 Pierstorff Lane');
insert into student (sname, address) values ('Ezra Lafee', '0738 Maywood Hill');
insert into student (sname, address) values ('Holly Duesberry', '69 Morning Junction');
insert into student (sname, address) values ('Dorita Sanchis', '42769 Atwood Avenue');
insert into student (sname, address) values ('Vevay Mowsdell', '690 Mosinee Avenue');
insert into student (sname, address) values ('Dane Gulc', '38 Swallow Avenue');
insert into student (sname, address) values ('Opal Rainville', '8 Mitchell Plaza');
insert into student (sname, address) values ('Gaynor Lowman', '0839 Anthes Center');
insert into student (sname, address) values ('Jacquelynn Zywicki', '64000 La Follette Drive');
insert into student (sname, address) values ('Silvester Mariolle', '6 Bartillon Hill');
insert into student (sname, address) values ('Luce Huckster', '770 Memorial Place');
insert into student (sname, address) values ('Meggi Alp', '01065 Gulseth Junction');
insert into student (sname, address) values ('Yelena Diver', '7934 Sachtjen Terrace');
insert into student (sname, address) values ('Kiah Peachment', '1 Clarendon Avenue');
insert into student (sname, address) values ('Lynnett Maggorini', '14451 Arkansas Hill');
insert into student (sname, address) values ('Sharity Cridland', '0622 Carey Street');
insert into student (sname, address) values ('Giff Gotcliffe', '818 Grayhawk Junction');
insert into student (sname, address) values ('Gay Ivchenko', '39 Crownhardt Plaza');
insert into student (sname, address) values ('Evita Fairbrace', '9283 Hoepker Circle');
insert into student (sname, address) values ('Pearl Grass', '95930 Crescent Oaks Terrace');
insert into student (sname, address) values ('Jeni Sidey', '7287 Shopko Junction');
insert into student (sname, address) values ('Alfy Incogna', '2746 Mallard Street');
insert into student (sname, address) values ('Jasmin Bickerdike', '172 Graceland Pass');
insert into student (sname, address) values ('Marnia Nuzzi', '4 Rutledge Street');
insert into student (sname, address) values ('Aile Mangam', '13926 Merchant Point');
insert into student (sname, address) values ('Normy Edmunds', '78 Fuller Lane');
insert into student (sname, address) values ('Claudia Helleckas', '9 Bunting Point');
insert into student (sname, address) values ('Gaile Bartrap', '5 Goodland Center');
insert into student (sname, address) values ('Raleigh Frisby', '173 Merchant Pass');
insert into student (sname, address) values ('Adah Veart', '1 Corben Way');
insert into student (sname, address) values ('Paddie Fairbrother', '75 Lake View Hill');
insert into student (sname, address) values ('Morly Rivard', '43 Union Lane');
insert into student (sname, address) values ('Amelita Dunkerk', '375 Little Fleur Terrace');
insert into student (sname, address) values ('Britni Ascraft', '7480 Blue Bill Park Pass');
insert into student (sname, address) values ('Calla Prene', '87 Anniversary Street');
insert into student (sname, address) values ('Cameron Attersoll', '31 Cottonwood Place');
insert into student (sname, address) values ('Lettie Kasper', '899 Mayfield Crossing');
insert into student (sname, address) values ('Meade Leynagh', '0283 Hayes Lane');
insert into student (sname, address) values ('Bayard Barends', '863 Barby Terrace');
insert into student (sname, address) values ('Levin Roddan', '67 Longview Road');
insert into student (sname, address) values ('Merola Duhig', '06786 Lotheville Pass');
insert into student (sname, address) values ('Gigi Spenceley', '91060 Killdeer Hill');
insert into student (sname, address) values ('Jennifer Sawday', '54387 Farwell Circle');
insert into student (sname, address) values ('Cristin Tuther', '7631 Eggendart Place');
insert into student (sname, address) values ('Billye Blunkett', '7672 Nancy Avenue');
insert into student (sname, address) values ('Ailene Teal', '717 Hazelcrest Alley');
insert into student (sname, address) values ('Cam Coutthart', '4550 Reindahl Hill');
insert into student (sname, address) values ('Nicky Erskine', '88 Talmadge Way');
insert into student (sname, address) values ('Randee Bruckental', '7 Rusk Plaza');
insert into student (sname, address) values ('Morey Falconbridge', '2 Crownhardt Plaza');
insert into student (sname, address) values ('Garvey Dossit', '4 Corscot Plaza');
insert into student (sname, address) values ('Robbyn Vel', '843 Sutteridge Alley');
insert into student (sname, address) values ('Wylma Minthorpe', '229 Reinke Avenue');
insert into student (sname, address) values ('Bartholomeo Catlin', '8311 Scott Place');
insert into student (sname, address) values ('Mattie Crumpton', '544 Manufacturers Plaza');
insert into student (sname, address) values ('Shurlocke Barents', '5003 Forest Run Drive');
insert into student (sname, address) values ('Jenn Hilliam', '2 Hagan Plaza');
insert into student (sname, address) values ('Tabbitha Earles', '09828 Crowley Place');
insert into student (sname, address) values ('Genni Frunks', '69 Namekagon Avenue');
insert into student (sname, address) values ('Madelin Shinfield', '842 Ohio Pass');
insert into student (sname, address) values ('Oneida Pickthorn', '01 Bellgrove Drive');
insert into student (sname, address) values ('Gael Ratlee', '81977 Service Junction');
insert into student (sname, address) values ('Maxwell Longlands', '9 Gerald Street');
insert into student (sname, address) values ('Gianni Murty', '657 Mandrake Pass');
insert into student (sname, address) values ('Fielding Guesford', '5 Crest Line Avenue');
insert into student (sname, address) values ('Wolfie Danilowicz', '1318 Holy Cross Way');
insert into student (sname, address) values ('Winston McRuvie', '248 Bartillon Avenue');
insert into student (sname, address) values ('Berk Pattemore', '42 Jackson Hill');
insert into student (sname, address) values ('Laughton Slott', '87 Westridge Avenue');
insert into student (sname, address) values ('Gaspard Rosindill', '659 Doe Crossing Pass');
insert into student (sname, address) values ('Lyndsay Verden', '34212 Sachtjen Circle');
